export enum KeyService {
  // auth
  LOGIN = "LOGIN",
  LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE",
  LOGIN_WITH_FACEBOOK = "LOGIN_WITH_FACEBOOK",
  SIGN_UP = "SIGN_UP",
  LOGOUT = "LOGOUT",
  LOGIN_WITH_PHONE = "LOGIN_WITH_PHONE",
  CONFIRM_OTP = "CONFIRM_OTP",

  // users
  GET_USER_SELF = "GET_USER_SELF",
  DISABLE_DEVICE_ID = "DISABLE_DEVICE_ID",
  SETUP_USER = "SETUP_USER",
  ADD_USER = "ADD_USER",

  // chat
  GET_HISTORY_CHAT_AI = "GET_HISTORY_CHAT_AI",
  SEND_PROMPT_AI = "SEND_PROMPT_AI",
  DELETE_CHAT_AI = "DELETE_CHAT_AI",

  // itinerary
  GET_ITINERARY = "GET_ITINERARY",

  // search
  SEARCH_PLACES = "SEARCH_PLACES",
}
